### ISSUE TITLE
Unsupported data type

### ISSUE THREAD

**Issue by haosdent** [haosdent/spark-hbase#5]
```
[info] HBaseSuite:
[info] - dsl test *** FAILED ***
[info]   java.io.IOException: Unsupported data type
[info]   at org.apache.hbase.spark.HBaseColumn$.apply(HBaseColumn.scala:65)
[info]   at org.apache.hbase.spark.HBaseSchema$$anonfun$3.apply(HBaseSchema.scala:40)
[info]   at org.apache.hbase.spark.HBaseSchema$$anonfun$3.apply(HBaseSchema.scala:36)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[info]   at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info]   at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
[info]   at org.apache.hbase.spark.HBaseSchema$.parseFrom(HBaseSchema.scala:35)
[info]   ...
[info] - sql test *** FAILED ***
[info]   java.lang.RuntimeException: [1.2] failure: ``INSERT'' expected but identifier CREATE found
[info]
[info]  CREATE TEMPORARY TABLE hbaseTable USING org.apache.hbase.spark OPTIONS (   table "spark_read_test",   schema "rowkey string, cf:qual1 int, cf:qual2 double",   hbase-site "/tmp/hbase-site.xml", )
```

**Comment by alexliu68** [comment]
How do you fix the issue of "[1.2] failure: ``INSERT'' expected but identifier CREATE found"?
